### ISSUE TITLE
Dropbox mirror is 404

### ISSUE THREAD

**Issue by RoxasShadow** [steveklabnik/CLOSURE#5]
Hello Steve,

it looks like that the link pointing to your Dropbox for the PDF mirror returns 404 - is there any possibility for the file to be recovered and uploaded again?

Thank you!

**Comment by kholbekj** [comment]
Opened a PR to update to a new dropbox link, as it'd be cool to have a mirror that is not github.
You don't really need kevinw's mirror, as you can just download that pdf from this repository directly.

https://github.com/steveklabnik/CLOSURE/pull/6
